name: Tests Font/Back
on:
  pull_request:
jobs:
  test_front:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/front

    strategy:
      matrix:
        node-version: [ latest ]


    steps:
      - name: Checkout-code
        uses: actions/checkout@v5

      - name: SetUp NodeJs
        uses: actions/setup-node@v4
        with:
           node-version: ${{ matrix.node-version }}

      - name: Install front dependencies
        run: npm install

      - name: Build front application
        run: npm run build --if-present

      - name: Run front tests with coverage
        run : npm run test:prod --if-present

      - name: Check coverage thresholds
        run: npm run check-coverage

      - name: Upload front tests coverage
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: front test code coverage
          path: ./front/coverage/bobapp

