name: Tests build scan and deploy app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test_front:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/front

    steps:
      - name: Checkout-code
        uses: actions/checkout@v5

      - name: SetUp NodeJs
        uses: actions/setup-node@v4
        with:
           node-version: latest

      - name: Install front dependencies
        run: npm install

      - name: Build front application
        run: npm run build --if-present

      - name: Run front tests with coverage
        run: npm run test:prod --if-present

      - name: Upload front tests coverage and build
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: front test code coverage and build
          path: |
            ./front/coverage/bobapp
            ./front/dist
            ./front/build
            

  test_back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/back

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Setup JAVA 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: install dependencies
        run: mvn clean install

      - name: run back tests and generate coverage report
        run: mvn clean verify

      - name: Backend code coverage report artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: JaCoCo code coverage and classes
          path: |
            ./back/target/site/jacoco/
            ./back/target/classes

  sonar_scan:
    name: Backend and Frontend sonar analysis
    runs-on: ubuntu-latest
    needs: [test_back, test_front]

    steps:
      - uses: actions/checkout@v5

      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
            name: JaCoCo code coverage and classes
            path: back/target

      - name: Download front artifacts
        uses: actions/download-artifact@v4
        with:
          name: front test code coverage and build
          path: front

      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker_backend:
    name: Build & Push Backend Docker
    runs-on: ubuntu-latest
    needs:
      - sonar_scan
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/bobapp-back:latest .

      - name: Push Docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/bobapp-back:latest

  docker_frontend:
    name: Build & Push Frontend Docker
    runs-on: ubuntu-latest
    needs:
        - sonar_scan
    defaults:
      run:
        working-directory: ${{ github.workspace }}/front

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest

